### ISSUE TITLE
The Gem has a huge issue: no secret returned

### ISSUE THREAD

**Issue by Dinuz** [bamorim/omniauth-dropbox-oauth2#1]
Dear @bamorin, 
thanks for this gem, but unfortunately it doesnt work properly.

I don't know if the issue is related with your gem or with the oauth2 dropbox api, but it's an heavy issue, because actually will not allow you to use the api in calls.

Briefly, in the hash[auth], in the credentials, is missing the secret (the token is returned but not the secret), this will compromise every potential future call to the api.

What do you think?

**Comment by bamorim** [comment]
Closing because it does not apply to oauth2 (Cleaning up the house)
