### ISSUE TITLE
OAuth2::Error

### ISSUE THREAD

**Issue by mmahalwy** [bamorim/omniauth-dropbox-oauth2#3]
I keep getting OAuth2::Error with the body of the HTML rendered by Dropbox as the error showing. Just not working at all. 
Set this as the callback: http://localhost:3000/auth/dropbox_oauth2/callback

is that right?

**Comment by yltsrc** [comment]
I get the same error
from logs:
```
[56ee3cc6-c86c-4dcc-a1f4-33e85840e6ae] Started GET "/users/auth/dropbox_oauth2/callback?state=STATE&code=CODE" for 10.0.2.2 at 2015-11-20 14:41:32 +0000
I, [2015-11-20T14:41:32.331715 #6888]  INFO -- omniauth: (dropbox_oauth2) Callback phase initiated.
E, [2015-11-20T14:41:33.576116 #6888] ERROR -- omniauth: (dropbox_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, invalid_grant: redirect_uri mismatch
{"error_description": "redirect_uri mismatch", "error": "invalid_grant"}
```

**Comment by robaman** [comment]
I've created PR https://github.com/bamorim/omniauth-dropbox-oauth2/pull/5 to get some discussion going about this. That one solved it for me, unsure if it solved it in a good way though.

**Comment by bamorim** [comment]
Hey, the last issue "redirect_uri mismatch" is probably related to intridea/omniauth-oauth2#81
The solution for me (on my last app using omniauth-instagram was to fix the omniauth-oauth2 version:
`gem 'omniauth-oauth2', '~> 1.3.1'`

@yltsrc and @robaman can you check this out?

Also, the error reported by @yltsrc does not seem to be related with the @mmahalwy issue.

And, given the opportunity that remembered me about this issue I want to say sorry to everyone for keeping this open without resolution. I was working to the bone in my last job that I've quit in July, now I'll have more time for OpenSource.

**Comment by bamorim** [comment]
@robaman Do you think It's better to fix the omniauth-oauth2 version or to apply the fix you've made? I'm waiting for a position from the omiauth-oauth2 maintainer. We should probably follow what the comunity is doing.

**Comment by robaman** [comment]
Looks like other strategy projects are using different methods for fixing it.

https://github.com/Shopify/omniauth-shopify-oauth2/commit/1a04cf0b4d168d91c0929dff731076bb04fb19ea

https://github.com/zquestz/omniauth-google-oauth2/commit/fc170504bf8273ec6601bf8ad75d98bf14260976

But with the extra info you provided me with I would probably give my vote to fixing it by setting the omniauth-oauth2 dependency to "~> 1.3.1" and waiting to see what happens after the 1.4.0 release of omniauth-oauth2.

**Comment by robaman** [comment]
Btw, tried that fix in my fork, and it worked for my project.

**Comment by robaman** [comment]
Just saw this specific comment: https://github.com/intridea/omniauth-oauth2/issues/81#issuecomment-151281907

We can probably regard that as an official statement from the project, right?

**Comment by bamorim** [comment]
@robaman pushed the new gem. (Something was wrong with the version in the version.rb of this repository. It was on 0.1.0 when the gem on the rubygems was a 0.2.0) I'll check this out tomorrow.

**Comment by robaman** [comment]
Thanks a lot!
