### ISSUE TITLE
Dropbox api version 2? - version 1 soon closed

### ISSUE THREAD

**Issue by ohenrik** [bamorim/omniauth-dropbox-oauth2#7]
Just a quick question, does this gem use Dropbox api v1 og v2? Dropbox will close the v1 api. And i assume that means that this gem will break if its using v1. 

I did a quick search and found that this gem uses `/1/oauth2/authorize` in its code. So this might mean that its using v1 api. 

Please read more here about migration. I might also be able to help.
https://www.dropbox.com/developers/reference/migration-guide

**Comment by bamorim** [comment]
Thank you for the warning. According to the guide we just need to change:
/1/oauth2/authorize to /oauth2/authorize;
/1/oauth2/token to /oauth2/token;
And we should change the way we get the account info.

But, there is a problem, however:
The account id changed from 1 to 2, which means it will be incompatible and
people should migrate it.

*Note:* In v1, user accounts included a uid field, an integer that
represented a user's Dropbox ID. In v2, we use account_id, which is a
string that represents the user's unique Dropbox ID. An account_id value
begins with the prefix "dbid" for an individual Dropbox account. Business
accounts also have team_member_ids, which begin with the prefix "dbmid." To
map uids toaccount_ids, use an access token to make a call to
/2/users/get_current_account, and map that value to the value you get from
/1/account/info.

I'll should add a note on the migration warning.

2016-06-28 18:39 GMT-03:00 Ole Henrik Skogstrøm <notifications@github.com>:

**Comment by bamorim** [comment]
@ohenrik  I'm without my main computer (it broke). Can you test the master branch for me?
Thank you. 😄

**Comment by ohenrik** [comment]
Ouch! sounds expensive, hope it's not too bad?

I tested it and it seems like there is something wrong here:
https://github.com/bamorim/omniauth-dropbox-oauth2/commit/9cbe6e4d0cd9698443eb80ecb40c51fa01415cfa#diff-6df13928ae34c7554ffb458c09ddbc8fR28

Added a comment there

**Comment by ohenrik** [comment]
I still can't get this gem to work. Please reopen this issue.

The problem is that the get raw_info method is sending a get request, and not post. Also when using the post request it is not sending with `Content-Type: application/json`, but with `Content-Type: application/x-www-form-urlencoded`. This is not accepted by dropbox.

Also it would be nice if you bumped up the version number so that we can install with bundle without refering to the master branch directly.

**Comment by nitanshu** [comment]
@ohenrik because in API v1 was following the REST and in API v2 it takes all request as POST so after changing so many things in the omniauth-dropbox-oauth2 faced the same problem but still didn't get  any solution.
